version: '3.1'

services:
    wordpress:
        image: wordpress
        restart: always
        ports:
            - 7070:80
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: wpuser
            WORDPRESS_DB_PASSWORD: '123456'
            WORDPRESS_DB_NAME: wordpress
        volumes:
            - wordpress:/var/www/html
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wpuser
            MYSQL_PASSWORD: '123456'
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes:
            - db:/var/lib/mysql
volumes:
    wordpress:
    db: