version: '2'
services:
  mysql-server: 
    image: 'daocloud.io/library/mysql:5.7.4'
    container_name: mysql-server
    environment:
      - MYSQL_ROOT_PASSWORD=root_pwd
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pwd
    restart: always
    volumes:
      - "/root/mysql/conf:/etc/mysql"
      - "/root/mysql/logs:/logs"
      - "/root/mysql/data:/var/lib/mysql"
  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix-server-mysql
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pwd
      - MYSQL_ROOT_PASSWORD=root_pwd
    restart: always
    links: 
      - mysql-server:mysql
    depends_on:
      - mysql-server
    ports:
      - "10051:10051"
  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix-web-nginx-mysql
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pwd
      - MYSQL_ROOT_PASSWORD=root_pwd
    restart: always
    links: 
      - mysql-server:mysql
      - zabbix-server-mysql:zabbix-server
    depends_on:
      - mysql-server
      - zabbix-server-mysql
    ports:
      - "82:80"
      - "8089:8080"
      - "8445:8443"